### ISSUE TITLE
[bug] Exec URL is not encoded properly

### ISSUE THREAD

**Issue by muratcakmakjengal** [renoki-co/laravel-php-k8s#16]
$pod->exec(['/bin/sh', '-c', "cd project/jengal && php artisan page-cache:clear $slug"]);
Because problem is  this '&' char.
My solution : url encode && = %26%26 
You can maybe general fix :)

**Comment by muratcakmaksoftware** [comment]
> Please let me know if there are any other issues. 👍

of course :) If I see any problem, I will inform you :)
